
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { Lead, PMReport } from '../types';

// Extend jsPDF with autotable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

export const exportPMReportToPDF = (report: PMReport) => {
  const doc = new jsPDF();
  const timestamp = new Date(report.date).toLocaleString();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(16, 185, 129); // emerald-500
  doc.text(report.title, 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`ID: ${report.id}`, 14, 30);
  doc.text(`Generated By: ${report.generatedBy}`, 14, 35);
  doc.text(`Date: ${timestamp}`, 14, 40);
  doc.text(`Status: ${report.status.toUpperCase()}`, 14, 45);

  // Content
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('Report Content:', 14, 60);
  
  doc.setFontSize(10);
  const splitContent = doc.splitTextToSize(report.content, 180);
  doc.text(splitContent, 14, 70);

  doc.save(`report_${report.id}_${Date.now()}.pdf`);
};

export const exportToPDF = (leads: Lead[], title: string = 'NEURAL_VAULT_REPORT') => {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();

  // Header
  doc.setFontSize(24);
  doc.setTextColor(16, 185, 129); // emerald-500
  doc.setFont('helvetica', 'bold');
  doc.text('SYNAPSE NEURAL VAULT', 14, 22);
  
  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(0.5);
  doc.line(14, 25, 196, 25);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.setFont('helvetica', 'normal');
  doc.text(`REPORT_TYPE: ${title}`, 14, 32);
  doc.text(`GENERATED_AT: ${timestamp}`, 14, 37);
  doc.text(`SYSTEM_STATUS: OPERATIONAL_V14`, 14, 42);

  // Stats
  const total = leads.reduce((a, b) => a + (b.revenuePerLead || 0), 0);
  const lost = leads.filter(l => l.fulfillmentOutcome === 'failure').reduce((a, b) => a + (b.revenuePerLead || 0), 0);
  const efficiency = total > 0 ? ((total - lost) / total) * 100 : 100;

  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(`Total Vault Value: $${total.toLocaleString()}`, 14, 45);
  doc.text(`Total Value Lost: $${lost.toLocaleString()}`, 14, 52);
  doc.text(`System Efficiency: ${efficiency.toFixed(1)}%`, 14, 59);

  // Table
  const tableData = leads.map(lead => [
    lead.name,
    lead.industry,
    lead.location,
    `${lead.readinessScore}%`,
    `$${(lead.revenuePerLead || 0).toLocaleString()}`,
    lead.queue,
    lead.fulfillmentOutcome || 'PENDING'
  ]);

  doc.autoTable({
    startY: 70,
    head: [['Node Descriptor', 'Industry', 'Location', 'Potency', 'Yield', 'Stage', 'Outcome']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [16, 185, 129] },
    styles: { fontSize: 8 }
  });

  doc.save(`${title.toLowerCase().replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};

export const exportToExcel = (leads: Lead[], title: string = 'NEURAL_VAULT_DATA') => {
  const worksheet = XLSX.utils.json_to_sheet(leads.map(lead => ({
    'Node Descriptor': lead.name,
    'Industry': lead.industry,
    'Location': lead.location,
    'Phone': lead.phone,
    'Email': lead.email,
    'Readiness Score': lead.readinessScore,
    'Revenue Per Lead': lead.revenuePerLead || 0,
    'Queue': lead.queue,
    'Fulfillment Outcome': lead.fulfillmentOutcome || 'PENDING',
    'Completed At': lead.completedAt || 'N/A',
    'Search Date': lead.searchDate
  })));

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Leads');
  XLSX.writeFile(workbook, `${title.toLowerCase().replace(/\s+/g, '_')}_${Date.now()}.xlsx`);
};

export const downloadReport = (leads: Lead[], type: string = 'MANUAL_FACTORY_EXPORT') => {
  exportToExcel(leads, type);
  exportToPDF(leads, type);
};

export const filterLeadsByTimeframe = (leads: Lead[], timeframe: 'daily' | 'weekly' | 'monthly') => {
  const now = new Date();
  const startOfTimeframe = new Date();

  if (timeframe === 'daily') {
    startOfTimeframe.setHours(0, 0, 0, 0);
  } else if (timeframe === 'weekly') {
    const day = now.getDay();
    const diff = now.getDate() - day + (day === 0 ? -6 : 1); // adjust when day is sunday
    startOfTimeframe.setDate(diff);
    startOfTimeframe.setHours(0, 0, 0, 0);
  } else if (timeframe === 'monthly') {
    startOfTimeframe.setDate(1);
    startOfTimeframe.setHours(0, 0, 0, 0);
  }

  return leads.filter(lead => {
    const date = lead.completedAt ? new Date(lead.completedAt) : new Date(lead.searchDate);
    return date >= startOfTimeframe;
  });
};
